name: app_environment
channels:
  - snowflake
dependencies:
  - altair=5.5.0
  - folium=0.14.0
  - plotly=6.0.1
  - pydeck=0.9.1
  - python=3.11.*
  - snowflake-snowpark-python=
  - streamlit=
  - streamlit-folium=0.15.0
